---
baseurl: https://awesome-arabic-speakers.dev/
languageCode: en-us
relativeURLs: true
paginate: 6
title: Awesome Arabic Speakers

services:
  googleAnalytics:
    id: G-TX4GN1CNZN

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

taxonomies:
  category: categories
  tag: tags
  language: languages
